/*
para poner un ENUM
*/

create type derivado_enum as ENUM ('si', 'no', 'ocd');
alter table pacientes
alter column derivado type derivado_enum
using derivado::derivado_enum

/*
para poner un ID autoincremental
*/

alter table provincia add column idProvincia serial primary key not null

************************

/*
para agregar una fk

use la interfaz grafica

- Abrí pgAdmin4 y conectate al servidor.
- Expandí Servers → tu base de datos → Schemas → public → Tables.
- Hacé clic derecho sobre la tabla donde querés agregar la foreign key → Properties.
- En el panel izquierdo, seleccioná "Constraints" → "Foreign Keys".
- Hacé clic en el ícono ➕ para agregar una nueva clave foránea.
- Completá los campos:
- Name: nombre de la constraint (ej. fk_paciente_id).
- Local column: la columna en esta tabla que será la foreign key.
- References: seleccioná la tabla destino (la que tiene la primary key).
- Referenced column: normalmente id o el campo clave primaria.
- Opcional: configurá acciones como ON DELETE o ON UPDATE.
- Guardá los cambios.

*/

CREATE TABLE IF NOT EXISTS public.diagnostico
(
    protocolopatologia_pk character varying COLLATE pg_catalog."default" NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    idenfermedad_fk integer,
    dateon date,
    primerdiagnostico boolean,
    recaida boolean,
    progresion boolean,
    segundaenfermedadmaligna boolean,
    biopsia boolean,
    cirugia "char",
    fechacirugia date,
    estadificacionchang character varying COLLATE pg_catalog."default",
    riesgo "char",
    riesgomotivo "char",
    localizacion "char",
    localizaciontext text COLLATE pg_catalog."default",
    idmolecular_fk integer,
    idtratamiento_fk integer,
    CONSTRAINT diagnostico_pkey PRIMARY KEY (protocolopatologia_pk)
);

*******************

create type cirugia_enum as ENUM ('no realizada', 'reseccion completa', 'near total resection', 'only biopsy', 'tve', 'enucleacion', 'exenteracion', 'septostomia', 'biopsia+tve', 'biopsia+septostomia', 'biopsia+derivacion ventricular', 'sin datos');
alter table diagnostico
alter column cirugia type cirugia_enum
using cirugia::cirugia_enum

***********************

create type estadificacionchang_enum as ENUM ('m0', 'm1', 'm2', 'm3', 'm4', 'sin datos');
alter table diagnostico
alter column estadificacionchang type estadificacionchang_enum
using estadificacionchang::estadificacionchang_enum


******************************

create type riesgo_enum as ENUM ('riesgo alto', 'riesgo estandar');
alter table diagnostico
alter column riesgo type riesgo_enum
using riesgo::riesgo_enum

******************************

create type riesgomotivo_enum as ENUM ('anaplasia', 'diseminado m1', 'diseminado m2', 'diseminado m3', 'cmyc', 'nmyc');
alter table diagnostico
alter column riesgomotivo type riesgomotivo_enum
using riesgomotivo::riesgomotivo_enum

******************************

create type localizacion_enum as ENUM ('diseminado', 'extra snc', 'fosa posterior', 'infratentorial', 'medular', 'nervio periferico', 'ojo bilateral', 'ojo derecho', 'ojo izquierdo', 'selar supraselar', 'supratentorial');
alter table diagnostico
alter column localizacion type localizacion_enum
using localizacion::localizacion_enum

******************************

CREATE TABLE public.tratamiento
(
    idtratamiento_pk serial NOT NULL,
    hc_fk character varying,
    protocolopatologia_fk character varying,
    "yes/no" boolean,
    protocoloquimio text,
    radioterapiacampo text,
    radioterapiadosis text,
    medicaciontarget text,
    inmunoterapia text,
    PRIMARY KEY (idtratamiento_pk),
    CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
        REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT protocolopatologia_fk FOREIGN KEY (protocolopatologia_fk)
        REFERENCES public.diagnostico (protocolopatologia_pk) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE IF EXISTS public.tratamiento
    OWNER to postgres;

******************************

create type kiaabraf_enum as ENUM ('detectado', 'no detectado', 'no realizado', 'sin biopsia', 'externa - sin datos', 'no evaluable');
alter table molecular
alter column kiaabraf type kiaabraf_enum
using kiaabraf::kiaabraf_enum

create type v600_enum as ENUM ('detectado', 'no detectado', 'no realizado', 'sin biopsia', 'externa - sin datos', 'no evaluable');
alter table molecular
alter column v600 type v600_enum
using v600::v600_enum

******************************

create type statuslastfollowup_enum as ENUM ('vivo con enfermedad', 'vivo sin enfermedad', 'fallecido');
alter table followup
alter statuslastfollowup type statuslastfollowup_enum
using statuslastfollowup::statuslastfollowup_enum

******************************

/* codigo de la base
*/

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.diagnostico
(
    protocolopatologia_pk character varying COLLATE pg_catalog."default" NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    idenfermedad_fk integer,
    dateon date,
    primerdiagnostico boolean,
    recaida boolean,
    progresion boolean,
    segundaenfermedadmaligna boolean,
    biopsia boolean,
    cirugia cirugia_enum,
    fechacirugia date,
    estadificacionchang estadificacionchang_enum,
    riesgo riesgo_enum,
    riesgomotivo riesgomotivo_enum,
    localizacion localizacion_enum,
    localizaciontext text COLLATE pg_catalog."default",
    idmolecular_fk integer,
    idtratamiento_fk integer,
    CONSTRAINT diagnostico_pkey PRIMARY KEY (protocolopatologia_pk)
);

CREATE TABLE IF NOT EXISTS public.enfermedad
(
    idenfermedad_pk serial NOT NULL,
    tumor character varying COLLATE pg_catalog."default",
    CONSTRAINT enfermedad_pkey PRIMARY KEY (idenfermedad_pk)
);

CREATE TABLE IF NOT EXISTS public.followup
(
    idfollowup_pk serial NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    fechalastfollowup date,
    fechaobito date,
    statuslastfollowup statuslastfollowup_enum,
    lostfollowup boolean,
    CONSTRAINT followup_pkey PRIMARY KEY (idfollowup_pk)
);

CREATE TABLE IF NOT EXISTS public.medicocabecera
(
    idmedicocabecera_pk integer NOT NULL,
    medico character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT medicocabecera_pkey PRIMARY KEY (idmedicocabecera_pk)
);

ALTER TABLE public.medicocabecera
    ADD COLUMN matricula INTEGER,
    ADD COLUMN direccion TEXT,
    ADD COLUMN telefono BIGINT CHECK (telefono BETWEEN 0 AND 999999999999);

CREATE TABLE IF NOT EXISTS public.molecular
(
    idmolecular_pk serial NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    protocolopatologia_fk character varying COLLATE pg_catalog."default",
    kiaabraf kiaabraf_enum,
    v600 v600_enum,
    secuenciacion text COLLATE pg_catalog."default",
    metilacionresultado text COLLATE pg_catalog."default",
    ngssomatico text COLLATE pg_catalog."default",
    ngsgerminal text COLLATE pg_catalog."default",
    CONSTRAINT molecular_pkey PRIMARY KEY (idmolecular_pk)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    hc_pk character varying COLLATE pg_catalog."default" NOT NULL,
    apellido character varying COLLATE pg_catalog."default",
    nombre character varying COLLATE pg_catalog."default",
    fechanacimiento date,
    derivado derivado_enum,
    provincia_fk integer,
    smegenetico_fk integer,
    medicocabecera_fk integer,
    idfollowup_fk integer,
    CONSTRAINT pacientes_pkey PRIMARY KEY (hc_pk)
);

CREATE TABLE IF NOT EXISTS public.provincia
(
    idprovincia_pk integer NOT NULL DEFAULT nextval('provincia_idprovincia_seq'::regclass),
    provincia character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT provincia_pkey PRIMARY KEY (idprovincia_pk)
);

CREATE TABLE IF NOT EXISTS public.smegenetico
(
    idsmegenetico_pk integer NOT NULL,
    smegenetico character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT smegenetico_pkey PRIMARY KEY (idsmegenetico_pk)
);

CREATE TABLE IF NOT EXISTS public.tratamiento
(
    idtratamiento_pk serial NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    protocolopatologia_fk character varying COLLATE pg_catalog."default",
    "yes/no" boolean,
    protocoloquimio text COLLATE pg_catalog."default",
    radioterapiacampo text COLLATE pg_catalog."default",
    radioterapiadosis text COLLATE pg_catalog."default",
    medicaciontarget text COLLATE pg_catalog."default",
    inmunoterapia text COLLATE pg_catalog."default",
    CONSTRAINT tratamiento_pkey PRIMARY KEY (idtratamiento_pk)
);

ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
    REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idenfermedad_fk FOREIGN KEY (idenfermedad_fk)
    REFERENCES public.enfermedad (idenfermedad_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idmolecular_fk FOREIGN KEY (idmolecular_fk)
    REFERENCES public.molecular (idmolecular_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idtratamiento_fk FOREIGN KEY (idtratamiento_fk)
    REFERENCES public.tratamiento (idtratamiento_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.followup
    ADD CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
    REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.molecular
    ADD CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
    REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.molecular
    ADD CONSTRAINT protocolopatologia_fk FOREIGN KEY (protocolopatologia_fk)
    REFERENCES public.diagnostico (protocolopatologia_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT idfollowup_fk FOREIGN KEY (idfollowup_fk)
    REFERENCES public.followup (idfollowup_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT medicocabecera_fk FOREIGN KEY (medicocabecera_fk)
    REFERENCES public.medicocabecera (idmedicocabecera_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT provincia_fk FOREIGN KEY (provincia_fk)
    REFERENCES public.provincia (idprovincia_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT smegenetico_fk FOREIGN KEY (smegenetico_fk)
    REFERENCES public.smegenetico (idsmegenetico_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tratamiento
    ADD CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
    REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tratamiento
    ADD CONSTRAINT protocolopatologia_fk FOREIGN KEY (protocolopatologia_fk)
    REFERENCES public.diagnostico (protocolopatologia_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;

CREATE TABLE IF NOT EXISTS public.obrasocial
(
    idobrasocial_pk SERIAL PRIMARY KEY,
nombre_os VARCHAR(100),
plan VARCHAR(50),
numero_cobertura INTEGER,
telefono INTEGER,
cronico BOOLEAN
);


CREATE TYPE nombre_os AS ENUM (
    'OSDE',
    'Swiss Medical',
    'Galeno',
    'IOMA',
    'Medicus',
    'Hospital Italiano',
    'Accord Salud',
    'Omint',
    'Sancor Salud',
    'Federada Salud',
    'OSECAC',
    'Unión Personal',
    'Luis Pasteur',
    'AMFFA',
    'OSPAT',
    'OSDEPYM',
    'OSDOP',
    'OSUTHGRA',
    'OSSEG',
    'OSPE',
    'OSPRERA'
);

ALTER TABLE public.obrasocial
ALTER COLUMN nombre_os TYPE nombre_os
USING nombre_os::nombre_os;


/* 

-- This script was generated by the ERD tool in pgAdmin 4.
-- 7 de diciembre 2025 update

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.diagnostico
(
    protocolopatologia_pk character varying COLLATE pg_catalog."default" NOT NULL,
    hc_fk character varying COLLATE pg_catalog."default",
    idenfermedad_fk integer,
    dateon date,
    primerdiagnostico boolean,
    recaida boolean,
    progresion boolean,
    segundaenfermedadmaligna boolean,
    biopsia boolean,
    cirugia cirugia_enum,
    fechacirugia date,
    estadificacionchang estadificacionchang_enum,
    riesgo riesgo_enum,
    riesgomotivo riesgomotivo_enum,
    localizacion localizacion_enum,
    localizaciontext text COLLATE pg_catalog."default",
    idmolecular_fk integer,
    idtratamiento_fk integer,
    CONSTRAINT diagnostico_pkey PRIMARY KEY (protocolopatologia_pk)
);

CREATE TABLE IF NOT EXISTS public.enfermedad
(
    idenfermedad_pk serial NOT NULL,
    tumor character varying COLLATE pg_catalog."default",
    who_grade integer,
    CONSTRAINT enfermedad_pkey PRIMARY KEY (idenfermedad_pk)
);

CREATE TABLE IF NOT EXISTS public.followup
(
    idfollowup_pk serial NOT NULL,
    fechalastfollowup date,
    fechaobito date,
    statuslastfollowup statuslastfollowup_enum,
    lostfollowup boolean,
    CONSTRAINT followup_pkey PRIMARY KEY (idfollowup_pk)
);

CREATE TABLE IF NOT EXISTS public.medicocabecera
(
    idmedicocabecera_pk integer NOT NULL,
    medico character varying COLLATE pg_catalog."default" NOT NULL,
    matricula integer,
    direccion text COLLATE pg_catalog."default",
    telefono bigint,
    CONSTRAINT medicocabecera_pkey PRIMARY KEY (idmedicocabecera_pk)
);

CREATE TABLE IF NOT EXISTS public.molecular
(
    idmolecular_pk serial NOT NULL,
    kiaabraf kiaabraf_enum,
    v600 v600_enum,
    secuenciacion text COLLATE pg_catalog."default",
    metilacionresultado text COLLATE pg_catalog."default",
    ngssomatico text COLLATE pg_catalog."default",
    ngsgerminal text COLLATE pg_catalog."default",
    CONSTRAINT molecular_pkey PRIMARY KEY (idmolecular_pk)
);

CREATE TABLE IF NOT EXISTS public.obrasocial
(
    idobrasocial_pk serial NOT NULL,
    nombre_os character varying(20) COLLATE pg_catalog."default",
    plan character varying(50) COLLATE pg_catalog."default",
    numero_cobertura integer,
    telefono integer,
    cronico boolean,
    CONSTRAINT obrasocial_pkey PRIMARY KEY (idobrasocial_pk)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    hc_pk character varying COLLATE pg_catalog."default" NOT NULL,
    apellido character varying COLLATE pg_catalog."default",
    nombre character varying COLLATE pg_catalog."default",
    fechanacimiento date,
    derivado derivado_enum,
    provincia_fk integer,
    smegenetico_fk integer,
    medicocabecera_fk integer,
    idfollowup_fk integer,
    idobrasocial_fk integer,
    CONSTRAINT pacientes_pkey PRIMARY KEY (hc_pk)
);

CREATE TABLE IF NOT EXISTS public.provincia
(
    idprovincia_pk integer NOT NULL DEFAULT nextval('provincia_idprovincia_seq'::regclass),
    provincia character varying COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(20) COLLATE pg_catalog."default",
    partido character varying(20) COLLATE pg_catalog."default",
    direccion character varying(30) COLLATE pg_catalog."default",
    piso integer,
    departamento character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT provincia_pkey PRIMARY KEY (idprovincia_pk)
);

CREATE TABLE IF NOT EXISTS public.smegenetico
(
    idsmegenetico_pk integer NOT NULL,
    smegenetico character varying COLLATE pg_catalog."default" NOT NULL,
    tecnica character varying(10) COLLATE pg_catalog."default",
    fecha date,
    CONSTRAINT smegenetico_pkey PRIMARY KEY (idsmegenetico_pk)
);

CREATE TABLE IF NOT EXISTS public.tratamiento
(
    idtratamiento_pk serial NOT NULL,
    yes_no boolean,
    protocoloquimio text COLLATE pg_catalog."default",
    radioterapiacampo text COLLATE pg_catalog."default",
    radioterapiadosis text COLLATE pg_catalog."default",
    medicaciontarget text COLLATE pg_catalog."default",
    inmunoterapia text COLLATE pg_catalog."default",
    CONSTRAINT tratamiento_pkey PRIMARY KEY (idtratamiento_pk)
);

ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT hc_fk FOREIGN KEY (hc_fk)
    REFERENCES public.pacientes (hc_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idenfermedad_fk FOREIGN KEY (idenfermedad_fk)
    REFERENCES public.enfermedad (idenfermedad_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idmolecular_fk FOREIGN KEY (idmolecular_fk)
    REFERENCES public.molecular (idmolecular_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.diagnostico
    ADD CONSTRAINT idtratamiento_fk FOREIGN KEY (idtratamiento_fk)
    REFERENCES public.tratamiento (idtratamiento_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT idfollowup_fk FOREIGN KEY (idfollowup_fk)
    REFERENCES public.followup (idfollowup_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT idobrasocial_fk FOREIGN KEY (idobrasocial_fk)
    REFERENCES public.obrasocial (idobrasocial_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT medicocabecera_fk FOREIGN KEY (medicocabecera_fk)
    REFERENCES public.medicocabecera (idmedicocabecera_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT provincia_fk FOREIGN KEY (provincia_fk)
    REFERENCES public.provincia (idprovincia_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT smegenetico_fk FOREIGN KEY (smegenetico_fk)
    REFERENCES public.smegenetico (idsmegenetico_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

*/